# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-09-11 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20190910_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
    ]
